services:
  - name: proxy
    type: web
    env: docker
    plan: free
    dockerfilePath: ''
    image: traefik:v2.9
    networks:
      - traefik-public
      - default
    envVars:
      - key: TRAEFIK_PUBLIC_NETWORK
        value: ${TRAEFIK_PUBLIC_NETWORK}
    ports:
      - port: 80
        hostPort: 80
      - port: 8090
        hostPort: 8080
    volumes:
      - path: /var/run/docker.sock
        mountPath: /var/run/docker.sock
        readOnly: true
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --api.insecure=true
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}

  - name: backend
    type: web
    env: docker
    plan: free
    buildCommand: docker build -t ${DOCKER_IMAGE_BACKEND}:${TAG-latest} ./backend
    startCommand: /start-reload.sh
    dockerfilePath: backend/Dockerfile
    dependsOn:
      - db
    volumes:
      - path: ./backend
        mountPath: /app
    envVars:
      - key: SERVER_HOST
        value: http://${DOMAIN}
    ports:
      - port: 8888
        hostPort: 8888
    labels:
      - traefik.enable=true
      - traefik.http.routers.${STACK_NAME}-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
      - traefik.http.services.${STACK_NAME}-backend.loadbalancer.server.port=80

  - name: frontend
    type: web
    env: docker
    plan: free
    buildCommand: docker build -t ${DOCKER_IMAGE_FRONTEND}:${TAG-latest} ./frontend
    startCommand: npm run dev -- --host
    dockerfilePath: frontend/Dockerfile.development
    volumes:
      - path: ./frontend
        mountPath: /app
      - path: /app/node_modules
        mountPath: /app/node_modules
    ports:
      - port: 5173
        hostPort: 5173
    labels:
      - traefik.enable=true
      - traefik.http.routers.${STACK_NAME}-frontend-http.rule=PathPrefix(`/`)
      - traefik.http.services.${STACK_NAME}-frontend.loadbalancer.server.port=5173

volumes:
  - name: app-db-data

networks:
  - name: traefik-public
    external: false
