services:
  - name: proxy
    type: web
    env: docker
    plan: free
    dockerfilePath: ''
    image: traefik:v2.9
    networks:
      - traefik-public
      - default
    envVars:
      - key: TRAEFIK_PUBLIC_NETWORK
        value: ${TRAEFIK_PUBLIC_NETWORK}
    ports:
      - port: 80
      - port: 8090
    volumes:
      - path: /var/run/docker.sock
        mountPath: /var/run/docker.sock
        readOnly: true
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --api.insecure=true
      - --entrypoints.web.address=:80
    labels:
      - key: traefik.enable
        value: "true"
      - key: traefik.docker.network
        value: traefik-public

  - name: db
    type: web
    env: docker
    plan: free
    dockerfilePath: ''
    image: mongo:latest
    volumes:
      - path: app-db-data
        mountPath: /data/db
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: ${MONGO_DB}
      - key: MONGO_INITDB_ROOT_USERNAME
        value: ${MONGO_USER}
      - key: MONGO_INITDB_ROOT_PASSWORD
        value: ${MONGO_PASSWORD}
    ports:
      - port: ${MONGO_PORT}

  - name: backend
    type: web
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildCommand: docker build -t ${DOCKER_IMAGE_BACKEND}:${TAG-latest} ./backend
    startCommand: /start-reload.sh
    dependsOn:
      - name: db
    volumes:
      - path: ./backend
        mountPath: /app
    envVars:
      - key: SERVER_HOST
        value: http://${DOMAIN}
    ports:
      - port: 8888
    labels:
      - key: traefik.enable
        value: "true"
   
